services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - twitter
    depends_on:
      - app

  app:
    build: ./src
    ports:
      - "8000:8000"
    networks:
      - twitter

networks:
  twitter:
    driver: bridge